# Generated by Django 4.1.1 on 2022-10-16 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_commonprofile_userprofile_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=300)),
                ('industry', models.CharField(max_length=200)),
                ('companySize', models.CharField(max_length=100)),
                ('specialties', models.CharField(max_length=300)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.commonprofile')),
            ],
        ),
    ]
