# Generated by Django 4.1.1 on 2022-11-19 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_experience_enddate'),
        ('organization', '0003_organization_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.OneToOneField(default=6, on_delete=django.db.models.deletion.CASCADE, to='profiles.website'),
            preserve_default=False,
        ),
    ]
