# Generated by Django 4.1.1 on 2022-11-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_user'),
        ('organization', '0006_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='usersApplied',
            field=models.ManyToManyField(to='profiles.userprofile'),
        ),
    ]
