# Generated by Django 4.1.1 on 2022-11-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_user'),
        ('organization', '0007_job_usersapplied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='usersApplied',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.userprofile'),
        ),
    ]
