# Generated by Django 4.1.1 on 2022-09-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.ManyToManyField(blank=True, related_name='userskills', to='profiles.skill'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='websites',
            field=models.ManyToManyField(blank=True, related_name='websites', to='profiles.website'),
        ),
    ]
