# Generated by Django 4.1.1 on 2022-10-16 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_alter_profile_skill_alter_profile_websites'),
    ]

    operations = [
        migrations.CreateModel(
            name='commonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('profilePic', models.ImageField(default='defaultProfile.jpg', upload_to='profileimage/')),
                ('coverImage', models.ImageField(default='cover.png', upload_to='coverImage/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('websites', models.ManyToManyField(blank=True, related_name='websites', to='profiles.website')),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('contactDetails', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.contact')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.commonprofile')),
                ('skill', models.ManyToManyField(blank=True, related_name='userskills', to='profiles.skill')),
            ],
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
