# Generated by Django 4.1.1 on 2022-11-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_experience_enddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile',
        ),
        migrations.AddField(
            model_name='contact',
            name='phoneCountryCode',
            field=models.CharField(default='+91', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='coverImage',
            field=models.ImageField(default='cover.png', upload_to='coverImage/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(default='defaultProfile.jpg', upload_to='profileimage/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='websites',
            field=models.ManyToManyField(blank=True, related_name='websites', to='profiles.website'),
        ),
        migrations.DeleteModel(
            name='commonProfile',
        ),
    ]
