# Generated by Django 4.1.1 on 2022-12-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_gender_userprofile_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='coverImage',
        ),
    ]
